# -*- coding: utf-8 -*-
#
# Documentação com Esfinge documentation build configuration file, created by
# sphinx-quickstart on Thu Aug 28 08:33:56 2014.
#

import sys
import os

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.pngmath',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos'
copyright = u'2015, Clediane de Araújo Guedes'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.0'
# The full version, including alpha/beta/rc tags.
release = '1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'pt_BR'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = project

#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'metadados.tex', u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos',
   u'Clediane de Araújo Guedes', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos', u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos[D[D',
     [u'Clediane de Araújo Guedes'], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos', u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos[D[D',
   u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos', 'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos', 'One line description of project.',
   'Miscellaneous'),
]


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos'
epub_author = u'Clediane de Araújo Guedes'
epub_publisher = u'Clediane de Araújo Guedes'
epub_copyright = u'2015, Clediane de Araújo Guedes'

# The basename for the epub file. It defaults to the project name.
#epub_basename = u'Padrão de Metadados do Repositório Institucional da UFRN: Tutorial para submissão de documentos[D[D'

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

